version: "3.1"
services:
  app-service:
    container_name: tel_bot
    build:
      dockerfile: /home/sardor/Backend/Project/Bots/TeleBot/TeleBot/DockerFile
    restart: always
    ports:
      - "9090:2004"
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
  postgres_db:
    container_name: postgres
    image: "postgres:15"
    restart: always
    ports:
      - "5434:5433"
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: root