version: "3.7"
services:
  app-service:
    container_name: telebot_bot
    build:
      dockerfile: /home/sardor/Backend/Project/Bots/TeleBot/TeleBot/DockerFile
    restart: always
    ports:
      - "9090:2004"
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    container_name: postgres
    image: "postgres:15"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bot_db
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: root